default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: perfilpublico_development

test:
  <<: *default
  database: perfilpublico_test

production:
  <<: *default
  database: perfilpublico_production
